HF_TOKEN = "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"
GEMINI_API = "AIzaSyDQPQr_pWALivoVPqIKC6TfHi4AsUBGMm0"
GOOGLE_API = "AIzaSyBHTIqsJNIWnDYO2sH7BByOziAeKCV4MJw"
SERPER_API = "b2c6cff35bd6afbf51f8dbd1579ce1ef398e0bfe"
BRAVE_API = "BSAJmztarEbwaHpEI5SqjwpdbIORM_T"