version: '3.8'

services:
  server:
    build:
      context: .
    working_dir: /app/Database
    command: ["python3", "Database/setup.py"]
    ports:
      - "8765:8765"  # Make sure this matches your server port
    networks:
      - app-network

  streamlit-app:
    build:
      context: .
    working_dir: /app
    depends_on:
      - server  # Waits for the server to start
    ports:
      - "8501:8501"  # Exposes Streamlit app on 8501
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
